### ISSUE TITLE
Dependencies missing when running with default values

### ISSUE THREAD

**Issue by taatuut** [grtjn/mlvagrant#107] opened 2017-01-24 08:38 UTC
When running vagrant provision with default options (CentOS 6.7, MarkLogic 8.0) MarkLogic fails to install due to missing dependencies, see part of log below. According to MarkLogic System Requirements System http://developer.marklogic.com/products/marklogic-server/requirements-8.0
'***The redhat-lsb, glibc, gdb, and cyrus-sasl-lib packages are required on Red Hat Enterprise Linux. Additionally, on 64-bit Red Hat Enterprise Linux, both the 32-bit and the 64-bit glibc packages are required.'. Apparently these are not present in the base box?

With project.properties set Centos 7.2 and update_os=true teh required dependencies are installed and MarkLogic installs succesfully. I guess update_os=true does the trick, did not try other OS / update_os combinations.

Regards,

Emil

==> vgtest-ml1: Installing ML using
/space/software/MarkLogic-RHEL7-8.0-6.1.x86_64.rpm ...
==> vgtest-ml1: error:
==> vgtest-ml1: Failed dependencies:
==> vgtest-ml1: libc.so.6(GLIBC_2.14)(64bit) is needed by
MarkLogic-8.0-6.1.x86_64
==> vgtest-ml1: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) is needed by
MarkLogic-8.0-6.1.x86_64
==> vgtest-ml1: libsasl2.so.3()(64bit) is needed by
MarkLogic-8.0-6.1.x86_64
==> vgtest-ml1: libc.so.6(GLIBC_2.14) is needed by
MarkLogic-8.0-6.1.x86_64
==> vgtest-ml1: MarkLogic: unrecognized service

**Comment by grtjn** [comment] 2017-03-20 20:21
This is probably caused by the fact that the RHEL7 instead of the RHEL6 installer was used for CentOS 6. The RPM should perhaps detect it is being deployed against wrong env, but apparently isn't doing that.

Anyhow, `MarkLogic-RHEL6-8.0-6.3.x86_64.rpm` gave no issues, closing ticket..

**Closed by grtjn** 2017-03-20 20:21 UTC
