### ISSUE TITLE
Tomcat error when running vagrant provision

### ISSUE THREAD

**Issue by robpml** [grtjn/mlvagrant#54] opened 2015-08-25 17:38 UTC
after setting up as per instructions, running these commands
`vagrant plugin install vagrant-hostmanager`
`vagrant up --no-provision`
and then
`vagrant provision`
the process errors with the following:

==> pure-test-ml1: Dependency Installed:
==> pure-test-ml1:   perl-Error.noarch 1:0.17015-4.el6      perl-Git.noarch 0:1.7.1-3.el6_4.1
==> pure-test-ml1:   rsync.x86_64 0:3.0.6-12.el6
==> pure-test-ml1: Complete!
==> pure-test-ml1: Initialized empty Git repository in /space/projects/pure-test.git/
==> pure-test-ml1: running /opt/vagrant/setup-tomcat.sh
==> pure-test-ml1: Loaded plugins: fastestmirror
==> pure-test-ml1: Loading mirror speeds from cached hostfile
==> pure-test-ml1:  * base: mirror.vorboss.net
==> pure-test-ml1:  * extras: centos.hyve.com
==> pure-test-ml1:  * updates: centos.hyve.com
==> pure-test-ml1: Setting up Install Process
==> pure-test-ml1: No package tomcat available.
==> pure-test-ml1: Error: Nothing to do
==> pure-test-ml1: error reading information on service tomcat: No such file or directory
==> pure-test-ml1: tomcat: unrecognized service
==> pure-test-ml1: Note: consider running Tomcat behind a firewall if you intend to keep it open!
==> pure-test-ml1: running /opt/vagrant/backup-yum-cache.sh
==> pure-test-ml1: cp: cannot create directory `/space/software/yum': Protocol error
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by grtjn** [comment] 2015-08-25 21:37
Dupe of #47. Can't reproduce locally anymore though..

**Comment by grtjn** [comment] 2015-08-26 06:52
@robpml can you check with latest updates if this still occurs?

**Comment by grtjn** [comment] 2015-09-02 11:10
closed for the time being..

**Closed by grtjn** 2015-09-02 11:10 UTC
